### PR TITLE
Support size attribute for log file configurations

### PR DESCRIPTION
**Pull request by dwcramer**

### CODE REVIEW

**Comment by tersmitten** [comment]
Thanks for the addition. Can you also add it to the `README.md`?

**Comment by dwcramer** [comment]
Readme updated.

**Comment by tersmitten** [comment]
I will merge it as soon as the build is done.

**Comment by dwcramer** [comment]
Thanks. Once that happens, will it be available immediately via tersmitten.logrotated or should I add the git repo to my requirements.yml?

**Comment by tersmitten** [comment]
I updated [Ansible galaxy](https://galaxy.ansible.com/detail#/role/4955), so you can use `tersmitten.logrotated` (`v1.0.2`)

**Comment by dwcramer** [comment]
Thanks for getting that in so quickly!

**Pull request merged**
